---
title: "get data from web"
author: "Yuqi Miao"
date: "10/10/2019"
output: html_document
---


```{r}
library(tidyverse)
library(rvest)
library(httr)
```

```{r}
url = "http://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm"
drug_use_xml = read_html(url)

drug_use_xml
```

## get all the data table from website
```{r}
drug_use_xml %>%
  html_nodes(css = "table") 
```

## get only one table

```{r}
(drug_use_xml %>% html_nodes(css = "table")) %>%
    .[[1]] %>% ## . everything before the last pipe %>% , thats why we use ( )
    html_table() %>% 
    slice(-1) ## remove the repeated note
## Normaly, this involves more steps to get a clear table, figure out what to remove
```

```{r}
nyc_cost = 
  read_html("https://www.bestplaces.net/cost_of_living/city/new_york/new_york") %>%
  html_nodes(css = "table") %>%
  .[[1]] %>%
  html_table(header = TRUE)
```

# select gadget
## get hp data


## select some elements
```{r}

hpsaga_title = 
  read_html("https://www.imdb.com/list/ls000630791/") %>% 
    html_nodes(".lister-item-header a") %>% 
    html_text()
hpsaga_money = 
  read_html("https://www.imdb.com/list/ls000630791/") %>% 
    html_nodes(":nth-child(7) span:nth-child(5)") %>% 
    html_text()
hpsaga_df = 
  tibble(
    title = hpsaga_html,   ##???
    money = hpsaga_money,)


## to find the right css selector, google may be works better than gadget
```

```{r}
url = "https://www.amazon.com/product-reviews/B00005JNBQ/ref=cm_cr_arp_d_viewopt_rvwer?ie=UTF8&reviewerType=avp_only_reviews&sortBy=recent&pageNumber=1"

dynamite_html = read_html(url)

review_titles = 
  dynamite_html %>%
  html_nodes(".a-text-bold span") %>%
  html_text()

review_stars = 
  dynamite_html %>%
  html_nodes("#cm_cr-review_list .review-rating") %>%
  html_text()

review_text = 
  dynamite_html %>%
  html_nodes(".review-text-content span") %>%
  html_text()

reviews = tibble(
  title = review_titles,
  stars = review_stars,
  text = review_text
)

```

# API

```{r}
nyc_water = 
  GET("https://data.cityofnewyork.us/resource/waf7-5gvc.csv") %>% 
  content()

```


```{r}
nyc_water = 
  GET("https://data.cityofnewyork.us/resource/waf7-5gvc.json") %>% 
  content("text") %>%
  jsonlite::fromJSON() %>%
  as_tibble()

## json is more usual
```

```{r}
brfss_smart2010 = 
  GET("https://data.cdc.gov/api/views/acme-vg9e/rows.csv?accessType=DOWNLOAD") %>% 
  content("parsed")

```

```{r}
poke = 
  GET("http://pokeapi.co/api/v2/pokemon/1") %>%
  content()

head(poke)
poke$name

```



